specVersion: 0.2.0
name: simplesubquery
version: 1.0.0
description: test simplesubquery
repository: https://github.com/alexwork455/simple-subquery.git
schema:
  file: ./schema.graphql
network:
  genesisHash: '0x91bc6e169807aaa54802737e1c504b2577d4fafedd5a02c10293b1cd60e39527'
  endpoint: https://rpc.api.moonbase.moonbeam.network
  dictionary: https://api.subquery.network/sq/subquery/moonriver-dictionary
  chaintypes:
    file: ./types.yaml
dataSources:
  - kind: substrate/Moonbeam
    startBlock: 1548734
    processor:
      file: ./node_modules/@subql/contract-processors/dist/moonbeam.js
      options:
        abi: erc20
        address: '0x64b14fc2adfa92d52d3029dc481f375bb405835a'
    assets:
      erc20:
        file: ./testABI.json
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleMoonriverEvent
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - Transfer(address indexed from,address indexed to,uint256 value)
              - null
              - null
              - null
        - handler: handleMoonriverCall
          kind: substrate/MoonbeamCall
          filter:
            function: approve(address to,uint256 value)
        - handler: handleMoonriverCall
          kind: substrate/MoonbeamCall
          filter:
            function: approve(address to,uint256 value)
